version: "3.9"

services:
  app:
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.envs.development
    build:
      context: .
    working_dir: /src
    command: sh -c "/scripts/run.sh"
    ports:
      - "8003:8003"
    volumes:
      - ./src:/src
      - ./data/web/static:/vol/web/static
      - ./data/web/media:/vol/web/media
    depends_on:
      - db

  db:
    image: postgres:16.6
    ports:
      - "5432:5432"
    volumes:
      - django-starter-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  django-starter-data: